### PR TITLE
create container.yaml for odcs multi-arch builds

### PR DESCRIPTION
**Pull request by jeffdyoung**
create container.yaml for odcs multi-arch builds
@dorzel @adammhaile Please review.

### CODE REVIEW

**Comment by dorzel** [comment]
+1

**Comment by jeffdyoung** [comment]
@ironcladlou @joelsmith Ok to merge? We need to get this in, so can @adammhaile to enable ppc64le builds for OCP.

**Review by joelsmith — APPROVED** [review]
:+1:

**Comment by jeffdyoung** [comment]
Dropping this. We won't be doing odcs builds in the near future. Thanks!

**Pull request closed without merging**
